language: ruby
branches:
  only:
  - production
rvm:
- 2.2.3
before_install:
- openssl aes-256-cbc -K $encrypted_3969df2ed48f_key -iv $encrypted_3969df2ed48f_iv
  -in ssh_key.enc -out ssh_key -d
- chmod 600 ssh_key
script:
- bundle install
- bundle exec jekyll build
- rm _site/*.enc _site/ssh_key
- rsync -az -e "ssh -i ssh_key" _site/ admingcc@william-few.dreamhost.com:/home/admingcc/vagrace.org/
addons:
  ssh_known_hosts:
  - william-few.dreamhost.com
