language: ruby
branches:
  only:
  - production
rvm:
- 2.2.3
before_install:
- mkdir ~\/.ssh
- openssl aes-256-cbc -K $encrypted_3969df2ed48f_key -iv $encrypted_3969df2ed48f_iv
  -in known_hosts.enc -out ~\/.ssh\/known_hosts -d
- openssl aes-256-cbc -K $encrypted_3969df2ed48f_key -iv $encrypted_3969df2ed48f_iv
  -in ssh_key.enc -out ~\/.ssh\/id_rsa -d
- gem install jekyll
script:
- bundle install
- bundle exec jekyll build
- rsync _site/ admingcc@william-few.dreamhost.com:/home/admingcc/vagrace.org/
